version: 0.0
os: linux
files:
  - source: petclinic.war
    destination: /opt/tomcat/webapps/ROOT.war
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: deployscripts/preInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployscripts/postInstall.sh
      timeout: 300
      runas: root