version: 0.0
os: linux
files:
  - source: petclinic.war
    destination: /opt/tomcat/webapps/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: preInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: postInstall.sh
      timeout: 300
      runas: root